### ISSUE TITLE
Active 2.4GHz RFID Ethernet Reader

### ISSUE THREAD

**Issue by plancalculus** [lynxSven/BeaconSocialInteraction#13]
Was verbirgt sich unter https://github.com/meriac/openbeacon-ng hinter "Active 2.4GHz RFID Ethernet Reader"? Wofür wird dieser genutzt bzw. was genau steckt hinter dieser Bezeichnung?

**Comment by lynxSven** [comment]
Zu finden in [Active 2,4 Ghz RFID Ethernet Reader](https://github.com/lynxSven/BeaconSocialInteraction/wiki/Active-2,4-Ghz-RFID-Ethernet-Reader)
