### ISSUE TITLE
Arduinoboard bewerten

### ISSUE THREAD

**Issue by lynxSven** [lynxSven/BeaconSocialInteraction#17]
Am Dienstag (21.10.2016) kriege ich ein Arduinoboard. 
Ich werde mich in die Thematik Zusammenbau und Programmierung der Boards einarbeiten und die Technik bewerten.

**Comment by plancalculus** [comment]
Bevor du Zeit in Zusammenbau und Programmierung steckst, bitte einmal eine Recherche anstellen, ob sich ein Arduino-Board für unsere Anwendung eignet. Ich sehe vor allem die folgenden Fragen.

- Gibt es Boards die so klein sind, dass man sie als Tag nutzen kann?
- Welche Spannungsversorgung benötigen die Boards?
- Wie ist in etwa der Kostenpunkt eines Boards?
- Gibt es Boards mit BLE-Chip?
