### ISSUE TITLE
Anfertigen einer Übersichtstabelle für die Beaconauswahl

### ISSUE THREAD

**Issue by reitbergerflorian** [lynxSven/BeaconSocialInteraction#19]
Zusammenführen der gesammelten Recherche-Ergebnisse bzgl. der in Frage kommenden Beacons in einer Tabellenübersicht. Die Vergleichsaufstellung soll die Beacon-Hardwares mit deren Funktionen, Größe, Kosten, Reichweite, etc. gegenüberstellen und als Hilfsstütze bei der Entscheidung der passenden Hardware dienen.

**Comment by reitbergerflorian** [comment]
Übersichtstabelle weitestgehend fertig. Weitere Überprüfung und Aktualisierung steht noch aus.
Wenn ihr noch was findet nur rein damit :-)

**Comment by reitbergerflorian** [comment]
Es liegt auch eine PDF im Dokumenten-Ordner - > Tabelle auf einen Blick

[Beaconübersicht.pdf](https://github.com/lynxSven/BeaconSocialInteraction/blob/master/documents/Beaconu%CC%88bersicht.pdf)

**Comment by plancalculus** [comment]
Ich vermute die Anmerkung "Android und iOS SDK" bezieht sich auf den Empfänger der Daten. Der Beacon selbst wird ja nicht mit den Android SDK programmiert.

**Comment by reitbergerflorian** [comment]
Nochmals genauer recherchiert. Jo ist ein Management-System für Android und iOS.
Tabelle wurde nach bestem Gewissen nochmals aktualisiert.

**Comment by reitbergerflorian** [comment]
[Übersicht der Beacons] (https://github.com/lynxSven/BeaconSocialInteraction/wiki/%C3%9Cbersicht-der-Beacons)
Bei Bedarf noch aktualisieren

**Comment by reitbergerflorian** [comment]
Übersicht der Beacons aktualisiert:
[Übersicht der Beacons](https://github.com/lynxSven/BeaconSocialInteraction/wiki/%C3%9Cbersicht-der-Beacons)
[Beaconübersicht_Version2.pdf
](https://github.com/lynxSven/BeaconSocialInteraction/blob/master/documents/Beaconu%CC%88bersicht_Version2.pdf)
