### ISSUE TITLE
Termin mit Professor Aschmoneit

### ISSUE THREAD

**Issue by plancalculus** [lynxSven/BeaconSocialInteraction#20]
Ich habe mich kurz mit Herrn Aschmoneit unterhalten und er kennt sich sehr gut im Bereich Mikrocontroller und Bluetooth aus. Die bisherigen Alternativen sollten einmal mit ihm diskutiert werden. Dazu muss ein Termin mit ihm vereinbart werden.

**Comment by reitbergerflorian** [comment]
Herr Aschmoneit ist aufgrund seiner Tätigkeiten als Dekanat sehr eingebunden. Wir konnten uns bestenfalls auf nächsten Dienstag zur Zeit unseres Projekttreffens einigen.

Ich bitte mich dafür zu entschuldigen.
Bin in zwei Wochen wieder dabei um zu berichten.

**Comment by lynxSven** [comment]
Wir könnten den Termin für nächste Woche auch verschieben, damit wir alle dahin kommen können und unser wöchentliches Projekttreffen vielleicht am Donnerstag nächste Woche machen können.

**Comment by reitbergerflorian** [comment]
Ich muss am Donnerstag und Freitag generell wegen meiner Arbeit passen

**Comment by reitbergerflorian** [comment]
Zusammenfassung der Disukssion:
[Beacon Microcontroller - Zusammenfassung der Diskussion vom 08.11.2016](https://github.com/lynxSven/BeaconSocialInteraction/wiki/Beacon-Microcontroller-%E2%80%93-Zusammenfassung-der-Diskussion-vom-08.11.2016)
