### ISSUE TITLE
puck.js Hardware

### ISSUE THREAD

**Issue by universal** [lynxSven/BeaconSocialInteraction#3]
Eine weitere, interessante Hardware-Alternative ist: http://www.puck-js.com/

**Comment by reitbergerflorian** [comment]
Moin Johannes,
wir haben uns mit puck.js schon auseinandergesetzt. Eine wirklich interessante Alternative.
So wie ich das sehe wären die aber etwas teurer und hätten auch nur eine Reichweite von 28m im Vergleich zum RuuviTag, welches wir angedacht hätten.

Ich denke hier wäre eine Vergleichsaufstellung angebracht

**Comment by plancalculus** [comment]
Welche Hardware wird von puck.js verwendet? Welche Hardware würde sich für die Verwendung mit Espurino anbieten?

Um die zweite Frage zu beantworten, könnte man den Entwickler von puck.js anschreiben. Das Ergebnis sollte im Wiki festgehalten werden.

**Comment by lynxSven** [comment]
Punkt 1: Aktualisiert in [Mögliche Beacons] (https://github.com/lynxSven/BeaconSocialInteraction/wiki/M%C3%B6gliche-Beacons)
Punkt 2: wird noch ermittelt
