### ISSUE TITLE
Espruino auf Waveshare-Platine aufspielen

### ISSUE THREAD

**Issue by universal** [lynxSven/BeaconSocialInteraction#4]
Um sich mit der Programmierung vertraut zu machen, erste Demos zu entwickeln eignen sich wahrscheinlich auch die Development-Boards: Ich habe hier ein Waveshare-Board (http://www.waveshare.com/nrf51822-eval-kit.htm) + ein weiteres Modul (http://www.waveshare.com/wiki/Core51822). Diese haben zwar keinerlei Bewegungs-Sensoren oder ähnliches, aber bieten vielleicht ja trotzdem eine nette Möglichkeit zum ausprobieren. Diese könnte ich Jan mal mitgeben, falls ihr daran Interesse habt :-)

**Comment by plancalculus** [comment]
Jemand (am besten Sven) müsste Johannes in Kiel besuchen und sich zeigen lassen, wie man Espruino auf die Waveshare-Platine aufspielt.

Als Ergebnis sollte eine kurze Anleitung im Wiki hinterlegt oder verlinkt werden. Außerdem sollte ein Treffen mit allen Teilnehmern stattfinden, um allen den Prozess zu zeigen.

**Comment by lynxSven** [comment]
Alles klar, ich treffe mich gerne mit Johannes und lass mir das zeigen. Johannes: Du müsstest mir Bescheid geben, wann du Zeit dafür hättest.

Noch kurz angemerkt: Ich komme wahrscheinlich an ein Arduinoboard. Ich lasse mir das auch zeigen und erklären. 
Die Programmiersprache ist an Processing angelehnt.

**Comment by plancalculus** [comment]
Bitte erstell für das Aduinoboard ein neues Ticket, in dessen Zuge die Technologie bewertet wird.

**Comment by universal** [comment]
Hmm... ich bin von Freitag bis Montag nicht in Kiel. Donnerstag habe ich bis 10Uhr Vorlesung, aber sonst findet sich eigentlich immer etwas Zeit. Schreib einfach mal einen Vorschlag wann es dir passen würde :-)

**Comment by lynxSven** [comment]
Wie wäre es mit Mittwoch gegen 10 - 12 Uhr?

**Comment by universal** [comment]
passt :-) Sitze an der Uni WSP7 - Raum 105 (meine ich zumindest, gerade umgezogen ;))

**Comment by lynxSven** [comment]
Alles klar. Ich kenne mich an der Kieler UNI nicht aus. Ich hoffe ich werde es finden

**Comment by lynxSven** [comment]
Funktioniert. Dokumentiert unter [Espurino auf einer Waveshareplatine aufspielen](https://github.com/lynxSven/BeaconSocialInteraction/wiki/Espruino-auf-einer-Waveshareplatine-aufspielen)
