### ISSUE TITLE
RuuviTag - Beacons noch nicht kostenlos

### ISSUE THREAD

**Issue by reitbergerflorian** [lynxSven/BeaconSocialInteraction#5]
Auf Nachfrage beim CEO Lauri Jämsä von Ruuvi Innovations Ltd. ist es zur Zeit noch nicht möglich für universitäre Forschungen kostenlose Beacons zu erhalten. Dies ist erst bei einer Massenanfertigung möglich.

Die Beacons kosten derweil noch soviel wie in der Kampagne ausgeschrieben:
https://www.kickstarter.com/projects/463050344/ruuvitag-open-source-bluetooth-sensor-beacon/description

**Comment by reitbergerflorian** [comment]
Die Beacons gibt es bis Ende November nur für 100 Euro/Stück. Erst im Dezember soll nach Lauri Jämsä ein Webshop eröffnet werden.
Der Kickstarter ist nicht aktuell.

**Comment by plancalculus** [comment]
Bitte die entsprechenden Informationen in das Wiki einpflegen, hier darauf verweisen und dann das Ticket schließen.

**Comment by lynxSven** [comment]
Aktualisiert in [Mögliche Beacons](https://github.com/lynxSven/BeaconSocialInteraction/wiki/M%C3%B6gliche-Beacons)
