### ISSUE TITLE
Platinen/Beacons mit nRF51822-Chip

### ISSUE THREAD

**Issue by plancalculus** [lynxSven/BeaconSocialInteraction#6]
Welche Platinen/Beacons mit dem nRF51822-Chip gibt es?

Das Ergebnis dieses Tickets sollte eine Tabelle/Liste mit den verschiedenen Platinen und ein Vergleich ihrer Features sein. Zum Beispiel, Funktionalität, Preis, ... Dabei sollen auch die bereits im Wiki aufgelisteten Lösungen berücksichtigt werden.

**Comment by lynxSven** [comment]
unter dem Punkt [Hardware mit nRF52832 Chip](https://github.com/lynxSven/BeaconSocialInteraction/wiki/Hardware-mit-nRF52832-Chip) zu finden

**Comment by plancalculus** [comment]
Der Title des Artikel enthält nRF52832, das Ticket war aber auf den nRF51822 bezogen. Bitte die Unterschiede herausarbeiten und entsprechend in diesen oder einen anderen Artikel einpflegen.

**Comment by lynxSven** [comment]
In den Artikel hinzugefügt
