### ISSUE TITLE
Evaluation der Programmierlösungen des micro:bit

### ISSUE THREAD

**Issue by plancalculus** [lynxSven/BeaconSocialInteraction#9]
Der BBC micro:bit bietet verschiedene Möglichkeiten, ein Mirco:bit zu programmieren (https://www.microbit.co.uk/create-code). Diese Möglichkeiten sollen erforscht und beurteilt werden.

Das Ergebnis dieses Tickets ist ein kurzer Wiki-Artikel, der die Möglichkeiten zusammenfasst und kurz in Bezug auf unser Projekt bewertet.

**Comment by reitbergerflorian** [comment]
Zu finden unter [BBC micro:bit Programmierlösungen](https://github.com/lynxSven/BeaconSocialInteraction/wiki/BBC-micro:bit-Programmierl%C3%B6sungen)

**Comment by universal** [comment]
http://www.espruino.com/MicroBit
